---

- name: wp theme activate sage-timber-wbba
  command: wp theme activate sage-timber-wbba --allow-root
  args:
    chdir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  with_dict: "{{ wordpress_sites }}"

